services:
  # PostgreSQL Database Service
  db:
    image: postgres:16-alpine
    container_name: rand-ai-reviewer-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: rand_ai_reviewer
      POSTGRES_USER: rand_user
      POSTGRES_PASSWORD: rand_password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rand_user -d rand_ai_reviewer"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - app_network

  # Backend Application Service
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: rand-ai-reviewer-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://rand_user:rand_password@db:5432/rand_ai_reviewer
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=rand_ai_reviewer
      - POSTGRES_USER=rand_user
      - POSTGRES_PASSWORD=rand_password
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - db
    networks:
      - app_network

  # Frontend Application Service  
  app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: rand-ai-reviewer-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://api:8000
    depends_on:
      - api
    networks:
      - app_network

volumes:
  postgres_data:
    driver: local

networks:
  app_network:
    driver: bridge
