"""add unique index for one main file per project revision

Revision ID: 3d1b6712406d
Revises: dbe72628c304
Create Date: 2026-08-31 15:25:22.433839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3d1b6712406d'
down_revision: Union[str, None] = 'dbe72628c304'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_files_one_main_per_project_revision', 'files', ['project_id', 'revision'], unique=True, postgresql_where=sa.text("role = 'main'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_files_one_main_per_project_revision', table_name='files', postgresql_where=sa.text("role = 'main'"))
    # ### end Alembic commands ###
