"""add extracted image columns to files

Revision ID: d7e75e8c6728
Revises: 3d1b6712406d
Create Date: 2026-09-01 10:38:24.382403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd7e75e8c6728'
down_revision: Union[str, None] = '3d1b6712406d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('parent_file_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_files_parent_file_id'), 'files', ['parent_file_id'], unique=False)
    op.create_foreign_key(None, 'files', 'files', ['parent_file_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.drop_index(op.f('ix_files_parent_file_id'), table_name='files')
    op.drop_column('files', 'parent_file_id')
    # ### end Alembic commands ###
