"""remove domain and target_audience from projects

Revision ID: dbe72628c304
Revises: ab0512d13ef0
Create Date: 2026-08-24 10:55:50.049351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dbe72628c304'
down_revision: Union[str, None] = 'ab0512d13ef0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'target_audience')
    op.drop_column('projects', 'domain')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('domain', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('target_audience', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
