// Bundles the repo's Agent Skills (../skills/<name>/SKILL.md) into a TypeScript
// module the /api/chat route can import at runtime. Run with `pnpm skills:generate`.
//
// We generate a committed file (rather than reading the filesystem at request
// time) because the frontend is deployed on its own — its Docker image only
// copies `frontend/`, so `../skills` is not present in production.

import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const frontendDir = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const skillsDir = resolve(frontendDir, '..', 'skills');
const outFile = resolve(frontendDir, 'lib', 'generated-skills.ts');

/** Split a SKILL.md into { name, description, instructions }. */
function parseSkill(markdown) {
  const match = markdown.match(/^---\n([\s\S]*?)\n---\n?([\s\S]*)$/);
  if (!match) return null;
  const [, frontmatter, body] = match;
  const name = frontmatter.match(/^name:\s*(.+)$/m)?.[1]?.trim();
  // `description` is the last frontmatter key and may span the rest of the block.
  const description = frontmatter.split(/^description:\s*/m)[1]?.trim();
  if (!name || !description) return null;
  return { name, description, instructions: body.trim() };
}

const skills = [];
for (const entry of readdirSync(skillsDir).sort()) {
  const skillPath = join(skillsDir, entry, 'SKILL.md');
  try {
    if (!statSync(join(skillsDir, entry)).isDirectory()) continue;
    const parsed = parseSkill(readFileSync(skillPath, 'utf8'));
    if (parsed) skills.push(parsed);
  } catch {
    // Skip directories without a readable SKILL.md.
  }
}

const contents = `// AUTO-GENERATED by scripts/generate-skills.mjs — do not edit by hand.
// Run \`pnpm skills:generate\` to refresh from ../skills.

export interface Skill {
  name: string;
  description: string;
  instructions: string;
}

export const SKILLS: Skill[] = ${JSON.stringify(skills, null, 2)};
`;

writeFileSync(outFile, contents);
console.log(`Wrote ${skills.length} skills to ${outFile}`);
