// Bundles the repo's Agent Skills (../skills/<name>/SKILL.md) into a TypeScript
// module the /api/chat route can import at runtime. Run with `pnpm skills:generate`.
//
// We generate a committed file (rather than reading the filesystem at request
// time) because the frontend is deployed on its own — its Docker image only
// copies `frontend/`, so `../skills` is not present in production.

import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const frontendDir = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const skillsDir = resolve(frontendDir, '..', 'skills');
const outFile = resolve(frontendDir, 'lib', 'generated-skills.ts');

/** Split a SKILL.md into { name, description, instructions }. */
function parseSkill(markdown) {
  const match = markdown.match(/^---\n([\s\S]*?)\n---\n?([\s\S]*)$/);
  if (!match) return null;
  const [, frontmatter, body] = match;
  const name = frontmatter.match(/^name:\s*(.+)$/m)?.[1]?.trim();
  // `description` is the last frontmatter key and may span the rest of the block.
  const description = frontmatter.split(/^description:\s*/m)[1]?.trim();
  if (!name || !description) return null;
  // A `<!-- interactive-only:start -->` / `<!-- interactive-only:end -->` pair
  // marks sections that only apply when a user is there to answer (asking for
  // web-search consent, for instance). The chat is exactly that setting, so the
  // sections stay — only the markers go, since the backend loader
  // (lib/skills.py) is what they exist for.
  const instructions = body.replace(/[ \t]*<!-- interactive-only:(?:start|end) -->[ \t]*\n?/g, '');
  return { name, description, instructions: instructions.trim() };
}

// Skills that exist under ../skills but are not part of Draft Detective. Draft
// Detective offers checks that review a draft the author already has; these two
// go looking for new literature instead, which is a different product. The
// SKILL.md files stay on disk — the backend workflows and any standalone use
// still read them — they are just left out of the chat catalogue and the
// slash-command menu. Keep this in step with lib/workflows/categories.py, which
// omits the matching workflows from the assessment picker.
const EXCLUDED_SKILLS = new Set(['literature-review', 'live-reports']);

const skills = [];
for (const entry of readdirSync(skillsDir).sort()) {
  if (EXCLUDED_SKILLS.has(entry)) continue;
  const skillPath = join(skillsDir, entry, 'SKILL.md');
  try {
    if (!statSync(join(skillsDir, entry)).isDirectory()) continue;
    const parsed = parseSkill(readFileSync(skillPath, 'utf8'));
    if (parsed) skills.push(parsed);
  } catch {
    // Skip directories without a readable SKILL.md.
  }
}

const contents = `// AUTO-GENERATED by scripts/generate-skills.mjs — do not edit by hand.
// Run \`pnpm skills:generate\` to refresh from ../skills.

export interface Skill {
  name: string;
  description: string;
  instructions: string;
}

export const SKILLS: Skill[] = ${JSON.stringify(skills, null, 2)};
`;

writeFileSync(outFile, contents);
console.log(`Wrote ${skills.length} skills to ${outFile}`);
