on: [pull_request]

jobs:
  lint:
    name: black formatter
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: reviewdog/action-black@v3.22.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          level: error
