name: Deploy to Railway

on:
  push:
    branches:
      - feature/deploy-workflow

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    if: github.ref == 'refs/heads/feature/deploy-workflow'
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Railway
        run: railway up -- --project=${{ env.PROJECT_ID }}

      - name: Run database migrations
        run: railway run -- --project=${{ env.PROJECT_ID }} uv run alembic upgrade head

  build-check:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        run: uv sync --frozen

      - name: Run basic checks
        run: |
          echo "Running basic health checks..."
          uv run python -c "from lib.config.env import config; print('Config loaded successfully')"
          echo "Build check passed!"
